# Generated by Django 5.2.5 on 2025-08-29 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participant_id',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
