# Generated by Django 5.2.5 on 2025-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_alter_chatroom_participant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('private_group', 'Private Group')], max_length=20),
        ),
    ]
